// <auto-generated />
using System;
using ASRWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASRWebApp.Migrations
{
    [DbContext(typeof(AsrContext))]
    partial class AsrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("ASRWebApp.Models.Room", b =>
                {
                    b.Property<string>("RoomID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("RoomID");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("ASRWebApp.Models.Slot", b =>
                {
                    b.Property<string>("RoomID");

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("StaffID")
                        .IsRequired();

                    b.Property<string>("StudentID");

                    b.HasKey("RoomID", "StartTime");

                    b.HasIndex("StaffID");

                    b.HasIndex("StudentID");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("ASRWebApp.Models.Staff", b =>
                {
                    b.Property<string>("StaffID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("StaffID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("ASRWebApp.Models.Student", b =>
                {
                    b.Property<string>("StudentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("StudentID");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("ASRWebApp.Models.Slot", b =>
                {
                    b.HasOne("ASRWebApp.Models.Room", "Room")
                        .WithMany("Slots")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ASRWebApp.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ASRWebApp.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID");
                });
#pragma warning restore 612, 618
        }
    }
}
